### ISSUE TITLE
Warning when installed in Ember v2.6.2

### ISSUE THREAD

**Issue by shijistar** [thefrontside/emberx-file-input#29] opened 2016-07-12 11:04 UTC
When I installed this addon, I got a warning saying,

```DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/home/lifengbao/Documents/udesk_crm_web/node_modules/ember-cli/lib/models/addon.js:896:27)```

Do you plan providing better support in newer version of Ember?

**Comment by cowboyd** [comment] 2016-07-12 11:17
Thanks for taking the time to report this. Fortunately, this was resolved recently with #28, and is a duplicate of #27.

Look for a new release to NPM this week. In the meantime, you can use master.

**Closed by cowboyd** 2016-07-12 11:17 UTC
